project:
  name: 'new-hampshire-real-estate-data-2026'
  description: ''
  version: 0.1.0

data:
  data_source: 'kanchana1990/new-hampshire-real-estate-data-2026'

data_quality:
  data_shape: (5009, 11)

  duplicates_detected: true
  duplicate_count: 80
  duplicates_removed: true

  missing_values_detected: true

data_leakage:
  checked: true

target_analysis:
  target_column: listPrice
  type_detected: continuous
  decision: regression